'use strict';

export default {
    FETCH_BUILD_INFO: 'FETCH_BUILD_INFO',
    FETCH_BUILD_INFO_REJECTED: 'FETCH_BUILD_INFO_REJECTED',
    FETCH_BUILD_INFO_FULFILLED: 'FETCH_BUILD_INFO_FULFILLED',
    FETCH_TAGGED_IMAGES: 'FETCH_TAGGED_IMAGES',
    FETCH_TAGGED_IMAGES_FULFILLED: 'FETCH_TAGGED_IMAGES_FULFILLED',
    FETCH_TAGGED_IMAGES_REJECTED: 'FETCH_TAGGED_IMAGES_REJECTED',
    SET_AUTH_STATUS: 'SET_AUTH_STATUS'
};